### ISSUE TITLE
MissingMethodException when upgrading troops while FrugalCavalry mod is installed

### ISSUE THREAD

**Issue by dss539** [tbeswick96/BannerlordYetAnotherPartyOrganiser#34]
I think some recent changes you made has caused a conflict with the FrugalCavalry mod. It might be a good idea to note the conflict in YAPO's description. Up until now, these 2 mods didn't seem to have any conflicts.  

I'm not sure the best way to resolve it, but it would be great if you could just bake FrugalCavalry behavior into YAPO.  

Anyhow, here is the stack trace that throws the `MissingMethodException`  

```
   at FrugalCavalry.PatchPartyScreenLogic.Prefix(PartyScreenLogic __instance, ItemCategory itemCategory, Int32 numOfItemsLeftToRemove)
   at TaleWorlds.CampaignSystem.PartyScreenLogic.UpgradeTroop(PartyCommand command)
   at YAPO.Services.TroopActionService.UpgradeTroops(PartyVM partyVm, PartyScreenLogic partyScreenLogic) in C:\src\repos\BannerlordYetAnotherPartyOrganiser\Extension\Services\TroopActionService.cs:line 56
   at YAPO.PartyVmMixin.UpgradeTroops() in C:\src\repos\BannerlordYetAnotherPartyOrganiser\Extension\PartyVmMixin.cs:line 200
   at YAPO.PartyVmMixin.ExecuteActionUpgrade() in C:\src\repos\BannerlordYetAnotherPartyOrganiser\Extension\PartyVmMixin.cs:line 683
```

**Comment by MLNW** [comment]
Which versions of Bannerlord/FrugalCavalry/YAPO were installed at the time of the crash?

**Comment by dss539** [comment]
Official branch (not beta, so 1.2 I guess), latest versions of all mods at
the time of writing.

Sorry I'm not near my PC right now to check exact versions.

**Comment by Urky** [comment]
Frugalcavalry replaced a method using Harmony.  However looks like there was a breaking change introduced by Taleworlds. Now that method that was replaced has the wrong methodsignature, hence the method FrugalCavalry tries to call does not exist.

I feel bad just adding the functionality without giving the frugalcav author the chance. I recommend switching the mod off and notify the author
